### ISSUE TITLE
Config Download Doesn't Capture Units in Zones

### ISSUE THREAD

**Issue by gregorymartin** [sushilks/kumojs#3]
I have grouped all the units upstairs in my home into a zone, when I run the config it seems to only pull back my main floor unit that is at the top level of my Kumo configuration.

here is the kumo.cfg

$ more kumo.cfg 
module.exports = 
{"username":{"key":{"serial":"key","label":"Main Floor","cryptoSerial":"serial","cryptoKeySet":"F","password":"password","address":"ip","S":0,"W":"guid"}}}
  
and here is a screenshot of my setup, there are 4 units in "Upstairs" that don't come through.

![June 05, 2019 at 1010PM](https://user-images.githubusercontent.com/1591110/59008280-e5d5e300-87de-11e9-806d-4743e2957f10.jpg)

**Comment by sushilks** [comment]
Do you want to a pull request for this problem ? Since I don't have the configuration you are testing it's hard for me to address it.

**Comment by gregorymartin** [comment]
Yeah, I will work on that.
