### ISSUE TITLE
Type errors on install

### ISSUE THREAD

**Issue by tmchow** [sushilks/kumojs#4]
I'm having all sorts of issues trying to even get this installed. I've got an Ubuntu 18.04 server running with Node 8.10 installed.

I installed typescript definitions after I got initiali errors trying to `sudo npm install kumojs`, so ran this:

`sudo npm install @types/node --save-dev`

Now I'm getting 4 errors from `src/kumojs.ts`:

```
src/kumojs.ts:60:25 - error TS2345: Argument of type 'unknown[]' is not assignable to parameter of type 'number[]'.
  Type 'unknown' is not assignable to type 'number'.

60                         Array.prototype.map.call(p+dt, function (m2:any) {
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
61                             return m2.charCodeAt(0)
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
62                         })
   ~~~~~~~~~~~~~~~~~~~~~~~~~~

src/kumojs.ts:75:43 - error TS2345: Argument of type 'number[]' is not assignable to parameter of type '[number, number, ...any[]]'.
  Type 'number[]' is missing the following properties from type '[number, number, ...any[]]': 0, 1

75         Array.prototype.splice.apply(dt3, [32, 32].concat(dt1_l));
                                             ~~~~~~~~~~~~~~~~~~~~~~

src/kumojs.ts:87:43 - error TS2345: Argument of type 'number[]' is not assignable to parameter of type '[number, number, ...any[]]'.

87         Array.prototype.splice.apply(dt3, [0, 32].concat(W))
                                             ~~~~~~~~~~~~~~~~~

src/kumojs.ts:124:57 - error TS2345: Argument of type 'Number' is not assignable to parameter of type 'number'.
  'number' is a primitive, but 'Number' is a wrapper object. Prefer using 'number' when possible.

124       return new Promise(resolve => setTimeout(resolve, ms));
                                                            ~~
Found 4 errors.
```

**Comment by sushilks** [comment]
what is the node version you are using?

**Comment by tmchow** [comment]
Confirmed it's `v8.10.0`

**Comment by abv** [comment]
I haven't gotten this fully working either, but resolved the above errors by downgrading from typescript 3 to typescript 2

**Comment by sushilks** [comment]
The package.json has the typescript version mentioned
    "typescript": "^2.4.2",
I am surprised it was not picked up from there. 
Did you run npm install in the directory where kumojs is located.

**Comment by tmchow** [comment]
@abv I tried installing Typescript 2.9.2 and still getting errors
@sushilks I'm just following your install directions in your README which says to run `npm install kumojs`.  Can you give a step by step on what we need to do to get this installed? Your current instructions seem insufficient.

**Comment by abv** [comment]
I had to `npm install -g typescript@2` -- for some reason the build script where referencing my global tsc, not the one in the package.

**Comment by rikbrown** [comment]
I was getting this issue too, even AFTER manually downgrading Typescript per @abv above.
So I made a patch so this runs with modern TypeScript instead: https://github.com/sushilks/kumojs/pull/13
