### ISSUE TITLE
Issues Installing

### ISSUE THREAD

**Issue by matthew-flagg** [sushilks/kumojs#6]
I've cloned the git repository and have npm installed.  I've tried running "npm install kumojs" from both the directory above the kumojs directory and within the kumojs directory.  From running in the parent directory it appears that  some of the files or directories are missing.  I'm attaching the debug log to help diagnose what I'm doing wrong.

[npm-debug.log](https://github.com/sushilks/kumojs/files/3406785/npm-debug.log)

**Comment by matthew-flagg** [comment]
Sorry, I was following the readme file assuming the top was the beginning of the steps.  I was able to get it up and running and was able to get responses via Postman.

**Comment by russalex83** [comment]
> 
> 
> Sorry, I was following the readme file assuming the top was the beginning of the steps. I was able to get it up and running and was able to get responses via Postman.

What is the correct way installing it? Thanks
